#!/usr/bin/env sh

adb push ./app/build/outputs/apk/debug/app-debug/classes.dex /data/local/tmp/
adb shell chmod 777  /data/local/tmp/classes.dex

#adb shell app_process -Djava.class.path=/data/local/tmp/classes.dex /data/local/tmp com.sogou.yarn.Main -layout
